# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('section_id', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=3)),
                ('credits', models.FloatField()),
                ('lecturer', models.CharField(max_length=75)),
                ('time_slot_1', models.IntegerField()),
                ('time_slot_2', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=8)),
                ('r_id', models.CharField(max_length=8)),
                ('alt_id', models.CharField(max_length=8)),
                ('parallel', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('section_id', models.CharField(max_length=8)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=3)),
                ('grade', models.CharField(max_length=4)),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
            ],
        ),
    ]
