# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('cid', models.CharField(db_column='cId', max_length=8, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'sequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.IntegerField(db_column='sId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registered',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='timeslots',
            options={'managed': False},
        ),
    ]
