# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_authuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'managed': False, 'verbose_name_plural': 'Courses/Sections'},
        ),
        migrations.AlterModelOptions(
            name='prerequisites',
            options={'managed': False, 'verbose_name_plural': 'Prerequisites'},
        ),
        migrations.AlterModelOptions(
            name='registered',
            options={'managed': False, 'verbose_name_plural': 'Registred Entries'},
        ),
        migrations.AlterModelOptions(
            name='sequence',
            options={'managed': False, 'verbose_name_plural': 'Sequence Entries'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False, 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='timeslots',
            options={'managed': False, 'verbose_name_plural': 'Timeslots'},
        ),
    ]
